# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ModularizediOSDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ModularizediOSDemo
#  pod 'CoreModule', :path => '../kmm/modules/CoreModule'
#  pod 'ProfileModule', :path => '../kmm/modules/ProfileModule'
  pod 'ModularizedSDK', :path => '../kmm/ModularizedSDK'

end
